
l = [
'Albany Municipal Civil Service Commission',
'Amsterdam Civil Service Commission, City of',
'Auburn City Civil Service Commission',
'Binghamton City Civil Service Commission',
'Buffalo City Department of Human Resources',
'Cohoes Civil Service Commission, City of',
'Fulton Municipal Civil Service Commission',
'Glen Cove Civil Service Commission, City of',
'Ithaca City Civil Service Commission',
'Kingston Civil Service Commission, City of',
'Lackawanna City Civil Service Commission',
'Lockport Civil Service Commission, City of',
'Long Beach Civil Service Commission, City of',
'Mechanicville City Civil Service Commission',
'Middletown City Civil Service Commission',
'Mount Vernon -Municipal Civil Service Commission, City of',
'New Rochelle City Civil Service Commission',
'Newburgh City Civil Service Commission',
'Niagara Falls City Civil Service Commission',
'Norwich City Civil Service Commission',
'Oneida City Civil Service Commission',
'Oneonta City Civil Service Commission',
'Oswego City Department of Personnel',
'Port Jervis City Civil Service Commission',
'Rochester City Civil Service Commission',
'Rome Civil Service Commission, City of',
'Saratoga Springs City Civil Service Commission',
'Sherrill City Personnel Office',
'Tonawanda City Civil Service Commission',
'Troy City Civil Service Commission',
'Utica City Civil Service Commission',
'Watertown City Civil Service Commission',
'Watervliet City Civil Service Commission',
'White Plains City Department of Personnel',
'Yonkers City Civil Service Commission',
'Albany County Department of Civil Service',
'Allegany County Human Resources/ Civil Service Department',
'Broome County Department of Personnel',
'Cattaraugus County Civil Service',
'Cayuga County Civil Service Commission',
'Chautauqua County Department of Human Resources',
'Chenango County Personnel/ Civil Service Office',
'Clinton County Department of Personnel',
'Columbia County Civil Service Commission',
'Cortland County Personnel/Civil Service Department',
'Delaware County Personnel Office',
'Dutchess County Department of Human Resources',
'Erie County Department of Personnel',
'Essex County Department of Personnel &Civil Service',
'Franklin County Personnel Office',
'Fulton County Personnel Department',
'Genesee County Personnel Department',
'Greene County Civil Service Commission',
'Hamilton County Personnel',
'Herkimer County Personnel Department',
'Jefferson County Department of Human Resources',
'Lewis County Department of Human Resources',
'Livingston County Personnel Office',
'Madison County Personnel/Civil Service Department',
'Monroe County Department of Human Resources',
'Montgomery County Personnel Department',
'Nassau County Civil Service Commission',
'Niagara County Civil Service',
'Oneida County Department of Personnel',
'Onondaga County Department of Personnel',
'Ontario County Department of Human Resources',
'Orange County Department of Human Resources',
'Orleans County Department of Personnel',
'Oswego County Human Resources Department',
'Otsego County Personnel Department',
'Putnam County Personnel Department',
'Rensselaer County Civil Service Commission',
'Rockland County Department of Personnel',
'Saratoga County Department of Personnel',
'Schenectady County Civil Service Commission',
'Schoharie County Department of Personnel',
'Schuyler County Civil Service Department',
'Seneca County Personnel Office',
'St. Lawrence County Human Resources Department',
'Steuben County Department of Personnel and Civil Service',
'Suffolk County Department of Civil Service',
'Sullivan County Personnel Department',
'Tioga County Personnel Office',
'Tompkins County Personnel Office',
'Ulster County Personnel Department',
'Warren County Department of Civil Service Administration',
'Washington County Personnel Office',
'Wayne County Personnel Department',
'Westchester County Department of Human Resources',
'Wyoming County Civil Service Commission',
'Yates County Personnel Department',
'NYC Dept of Citywide Administrative Services',
'New York City School Construction Authority',
'The City University of New York (Cuny), Office of Human Resources Management',
'Chemung/ Elmira Regional Civil Service Commission',
'Town of Colonie Civil Service Department',
'Town of Hempstead Civil Service Commission'
]






l2 = [
'Albany County',
'Albany City',
'Bethlehem Town',
'Cohoes City',
'Colonie Town',
'Guilderland Town',
'Watervliet City',
'Allegany County',
'Bronx County',
'Broome County',
'Binghamton City',
'Union Town',
'Vestal Town',
'Cattaraugus County',
'Cayuga County',
'Auburn City',
'Chautauqua County',
'Jamestown City',
'Chemung County',
'Elmira City',
'Chenango County',
'Norwich City',
'Clinton County',
'Columbia County',
'Cortland County',
'Delaware County',
'Dutchess County',
'East Fishkill Town',
'Poughkeepsie City',
'Poughkeepsie Town',
'Wappinger Town',
'Erie County',
'Amherst Town',
'Buffalo City',
'Lackawanna City',
'Tonawanda City',
'Essex County',
'Franklin County',
'Fulton County',
'Genesee County',
'Batavia City',
'Greene County',
'Herkimer County',
'Hamilton County',
'Jefferson County',
'Watertown City',
'Kings County',
'Lewis County',
'Livingston County',
'Madison County',
'Oneida City',
'Monroe County',
'Brighton Town',
'Chili Town',
'Rochester City',
'Greece Town',
'Irondequoit Town',
'Penfield Town',
'Perinton Town',
'Pittsford Town',
'Webster Town',
'Montgomery County',
'Nassau County',
'Glen Cove City',
'Hempstead Town',
'Hempstead Village',
'Long Beach City',
'North Hempstead Town',
'Oyster Bay Town',
'Rockville Centre Village',
'Valley Stream Village',
'New York City',
'City University of New York (CUNY)',
'Niagara County',
'Niagara Falls City',
'Lockport City',
'Oneida County',
'Rome City',
'Utica City',
'Onondaga County',
'Cicero Town',
'De Witt Town',
'Manlius Town',
'Syracuse City',
'Ontario County',
'Geneva City',
'Orange County',
'Middletown City',
'Monroe Town',
'Newburgh City',
'Wallkill Town',
'Orleans County',
'Oswego County',
'Oswego City',
'Otsego County',
'Oneonta City',
'Putnam County',
'Carmel Town',
'Queens County',
'Rensselaer County',
'Troy City',
'Richmond County',
'Rockland County',
'Clarkstown Town',
'Haverstraw Town',
'Orangetown Town',
'Ramapo Town',
'Spring Valley Village',
'Saratoga County',
'Clifton Park Town',
'Mechanicville',
'Saratoga Springs City',
'Schenectady County',
'Glenville Town',
'Rotterdam Town',
'Schenectady City',
'Schoharie County',
'Schuyler County',
'Seneca County',
'St Lawrence County',
'Ogdensburg',
'Steuben County',
'Suffolk County',
'Brookhaven Town',
'Huntington Town',
'Islip Town',
'Lindenhurst Village',
'Riverhead Town',
'Smithtown Town',
'Southampton Town',
'Sullivan County',
'Tioga County',
'Tompkins County',
'Ithaca City',
'Ulster County',
'Kingston City',
'Warren County',
'Glens Falls City',
'Washington County',
'Wayne County',
'Westchester County',
'Cortlandt Town',
'Eastchester Town',
'Greenburgh Town',
'Mount Vernon City',
'New Rochelle',
'Ossining Town',
'Ossining Village',
'Port Chester Village',
'Peekskill City',
'Rye City',
'White Plains City',
'Yonkers City',
'Yorktown Town',
'Wyoming County',
'Yates County'
]





for i in l:
    
    for ii in l2:

        f = i.split(' ')[0]
        if f in ii:
            break

    else: print(i)











'''Good afternoon,

I was wondering if the list of government civil service websites (located at https://labor.ny.gov/stats/cslist.shtm) will be updated soon. The page source has the following tag which leaves me to believe that the data is from ~ 2018:
<meta name="lastUpdated" content="Apr 11 2018" />

It seems that some websites appear to be missing from the list. Specifically:
City of Sherrill: https://sherrillny.org/city-hall/employment/
City of Geneva: http://cityofgenevany.com/available-positions/
City of Amsterdam: https://www.amsterdamny.gov/government/employment-opportunities

There may be others as well since I spent only a few minutes searching.

Thank you and have a good day.
'''



