



new = [
['franklinsquare.k12.ny.us/', 'http://franklinsquare.k12.ny.us/district_information/district_offices/office_of_personnel/employment_opportunities'],
['gcs.neric.org/', 'http://gcs.neric.org/about-us/employment'],
['nvcs.stier.org/', 'https://www.nvcs.stier.org/Employment.aspx'],
['phcs.neric.org/', 'https://www.phcsd.org/apps/pages/index.jsp?uREC_ID=1161786&type=d&pREC_ID=1415161'],
['saugerties.schoolwires.com/', 'https://www.applitrack.com/saugertiesk12/onlineapp/jobpostings/view.asp?internaltransferform.Url=&all=1'],
['stregisfallscsd.org/', 'http://stregisfallscsd.org/'],
['wayne.k12.ny.us/', 'https://waynecsd.recruitfront.com/JobOpportunities'],
['bcsdk12.org', 'https://www.applitrack.com/bcsdk12/onlineapp/default.aspx?all=1'],
['binghamtonschools.org', 'http://www.binghamtonschools.org/employment/employment_opportunities'],
['blindbrook.org/', 'http://www.blindbrook.org/'],
['boltoncsd.org/', 'https://www.boltoncsd.org/district/employment'],
['candor.org/', 'http://www.candorcsd.org/index.php/departments/employment/'],
['ccsdk12.org', 'https://sites.google.com/a/cantoncentral.org/human-resources/job-opportunities'],
['centralislip.k12.ny.us/', 'http://www.centralislip.k12.ny.us/administration/assistant_superintendent_for_personnel/employment_opportunities'],
['cooperstowncs.org/', 'https://www.cooperstowncs.org/o/cooperstown-csd/page/employment-opportunities-information'],
['crcs.k12.ny.us/', 'https://www.crcs.k12.ny.us/employment/'],
['croton-harmonschools.org/', 'http://www.croton-harmonschools.org/domain/346'],
['cvcsd.stier.org', 'https://www.cvcsd.stier.org/Employment.aspx'],
['depositcsd.org', 'https://www.depositcsd.org/Employment.aspx'],
['dolgeville.org/', 'http://www.dolgeville.org/district/employment_opportunities'],
['dryden.k12.ny.us/', 'https://www.dryden.k12.ny.us/departments/human_resources/job_openings'],
['dunkirkcsd.org', 'https://www.dunkirkcsd.org/site/default.aspx?PageType=3&DomainID=1&ModuleInstanceID=5543&ViewID=6446EE88-D30C-497E-9316-3F8874B3E108&RenderLoc=0&FlexDataID=6569&PageID=1'],
['eastchester.k12.ny.us/', 'http://www.eastchester.k12.ny.us/'],
['eastquogue.k12.ny.us/', 'http://www.olasjobs.org'],
['ecs.k12.ny.us/', 'http://www.ecs.k12.ny.us/district/district_information/employment_opportunities'],
['ellicottvillecentral.com', 'https://www.ellicottvillecentral.com/Domain/110'],
['elmiracityschools.com', 'http://www.elmiracityschools.com/employment.cfm'],
['elmontschools.org/', 'https://www.elmontschools.org/Page/381'],
['fallsburgcsd.net/', 'http://www.fallsburgcsd.net/district/employment'],
['fehb.org', 'http://www.fehb.org/o/franklin-essex-hamilton-boces/page/employment-opportunities--344'],
['fischool.com/', 'http://www.fischool.com/about_us/career_opportunities'],
['fortedward.org/', 'http://www.fortedward.org/district/job_opportunities'],
['gfsd.org/', 'https://www.gfsd.org/jobs'],
['greenecsd.org', 'https://www.greenecsd.org/Employment.aspx'],
['hastings.k12.ny.us/', 'https://www.applitrack.com/hohschools/onlineapp/default.aspx?all=1'],
['hauppauge.k12.ny.us/', 'http://www.hauppauge.k12.ny.us/Page/2668'],
['heightsschools.com', 'http://www.heightsschools.com/employment.cfm'],
['hfcsd.org/', 'https://www.hfcsd.org/district/employment/'],
['hopevale.com/ 51 118', '_CLOSED'],
['horseheadsdistrict.com', 'http://www.horseheadsdistrict.com/employment.cfm'],
['ilcsd.org/', 'https://www.ilcsd.org/home/district/administration'],
['jamestownpublicschools.org', 'https://www.jpsny.org/Page/2218'],
['johnsburgcsd.org/', 'http://www.johnsburgcsd.org/district/job_opportunities'],
['kingstoncityschools.org/', 'http://www.kingstoncityschools.org/domain/52'],
['kpcsd.k12.ny.us/', 'https://www.kpcsd.k12.ny.us/apps/pages/index.jsp?uREC_ID=346753&type=d'],
['lackawannaschools.org', 'http://www.lackawannaschools.org/departments_and_services/personnel_department/employment_opportunities'],
['lansingschools.org/', 'http://www.lansingschools.org/districtpage.cfm?pageid=1204'],
['lawrence.org/', 'http://www.lawrence.org/'],
['longwood.k12.ny.us/', 'http://www.longwood.k12.ny.us/departments/human_resources_department/Announcement_of_vacancy__Special_Education_Summer_'],
['lpschool.com/', 'http://www.lpschool.com'],
['lvcsd.k12.ny.us/', 'http://www.lvcsd.k12.ny.us/departments_and_programs/human_resources'],
['middleburgh.k12.ny.us/', 'https://www.middleburghcsd.org/about-us/employment-opportunities/'],
['minervasd.org/minervasd/site/default.asp', 'http://www.minervasd.org/minervasd/site/default.asp'],
['morriscs.org/', 'http://www.morriscs.org/district/employment'],
['mpbschools.org/', 'http://www.mpbschools.org/'],
['mpcsny.org', 'http://www.mpcsny.org'],
['mtplcsd.org', 'http://www.mtplcsd.org'],
['newark.k12.ny.us/', 'http://www.newark.k12.ny.us/Page/455'],
['newfieldschools.org/', 'http://www.newfieldschools.org/districtpage.cfm?pageid=109'],
['niskyschools.org/', 'https://www.niskayunaschools.org/employment'],
['nmerrickschools.org/', 'https://www.nmerrickschools.org/domain/487'],
['onteora.k12.ny.us/', 'http://www.onteora.k12.ny.us/departments/human-resources'],
['ossiningufsd.org/', 'https://ossiningufsd.org/departments/human-resources'],
['ovcs.org', 'https://www.ovcs.org/JobVacanices.aspx'],
['pavilioncsd.org/', 'http://www.pavilioncsd.org/employment'],
['pawlingschools.org', 'http://www.pawlingschools.org/human_resources'],
['pelhamschools.org/', 'https://www.pelhamschools.org/district/business-office/employment-opportunities'],
['pioneerschools.org', 'http://www.pioneerschools.org/domain/48'],
['randolphacademy.org', 'http://www.randolphacademy.org/district.html'],
['randolphcsd.org', 'http://www.randolphcsd.org/domain/24'],
['redhookcentralschools.org', 'https://www.redhookcentralschools.org/domain/24'],
['romecsd.org/', 'http://www.romecsd.org/district/people_operations'],
['rondout.k12.ny.us/', 'https://www.rondout.k12.ny.us/community/Employment'],
['roxburycs.org', 'https://www.roxburycs.org/EmploymentatRCS.aspx'],
['ryeneck.k12.ny.us/default.aspx', 'http://www.ryeneck.k12.ny.us/default.aspx'],
['salamancany.org', 'https://www.salamancany.org/Domain/11'],
['salemcsd.org/', 'http://www.salemcsd.org/district_information/job_opportunities'],
['saranac.org', 'http://www.saranac.org/home/employment'],
['schalmont.org/', 'https://www.schalmont.org/employment'],
['schenectady.k12.ny.us/', 'http://www.schenectady.k12.ny.us/departments/human_resources/seeking_employment'],
['srk12.org/', 'https://www.srk12.org/employment/'],
['svecsd.org/', 'http://www.svecsd.org/employment.cfm'],
['swcsd.org/', 'https://www.swcsd.org/Page/194'],
['tbafcs.org', 'http://www.tbafcs.org/Page/1444'],
['tupperlakecsd.net/', 'http://www.tupperlakecsd.net/'],
['vestal.k12.ny.us', 'http://www.vestal.k12.ny.us/Employment.aspx'],
['wccsk12.org/', 'https://www.wccsk12.org/page/2914'],
['wcsd.org/', 'http://www.wcsd.org/district/employment_opportunities'],
['websterschools.org', 'http://www.websterschools.org/districtpage.cfm?pageid=835'],
['weedsport.org', 'http://www.weedsport.org']
]





g = [
['Abbott Union Free School District', '_ERROR._url_not_found'],
['Alfred-Almond Central School District', 'http://www.aacs.wnyric.org/'],
['Allegany - Limestone Central School District', 'http://www.alli.wnyric.org'],
['Amagansett Union Free School District', 'http://www.amagansettschool.org/'],
['Arkport Central School District', 'http://acs.stev.net/'],
['Auburn City School District', 'http://district.auburn.cnyric.org'],
['Baldwin Union Free School District', 'http://www.baldwin.k12.ny.us/'],
['Ballston Spa Central School District', 'http://www.ballstonspa.k12.ny.us/'],
['Beaver River Central School District', 'http://www.brcsd.org'],
['Beekmantown Central School District', 'http://www.bcsdk12.org'],
['Bellmore Union Free School District', 'http://www.bellmore.k12.ny.us'],
['Bellmore-Merrick Central High School District', 'http://www.bellmore-merrick.k12.ny.us/', 'http://www.bellmore-merrick.k12.ny.us/district/opportunities', 'http://www.merrick.k12.ny.us/district/job_opportunities'],
['Bemus Point Central School District', 'http://www.mghs.org'],
['Berkshire Union Free School District', 'http://www.berkshirefarm.org'],
['Binghamton School District', 'http://www.binghamtonschools.org'],
['Blind Brook-Rye Union Free School District', 'http://www.blindbrook.org/'],
['Bolton Central School District', 'http://www.boltoncsd.org/'],
['Brentwood Union Free School District', 'http://www.brentwood.k12.ny.us/'],
['Bridgewater-West Winfield Central School District', 'http://www.mmcsd.org/'],
['Brighton Central School District', 'http://www.bcsd.org'],
['Brockport Central School District', 'http://www.brockport.k12.ny.us/'],
['Bronxville Union Free School District', 'http://www.bronxville.k12.ny.us/'],
['Brookfield Central School District', 'http://www.bcsbeavers.org'],
['Brunswick Central School District', 'http://www.brittonkill.k12.ny.us'],
['Brushton-Moira Central School District', 'http://www.fehb.org'],
['Burnt Hills-Ballston Lake Central School District', 'http://www.bhbl.org/'],
['Campbell-Savona Central School District', 'http://www.campbellsavona.wnyric.org/'],
['Canastota Central School District', 'http://www.canastotacsd.org'],
['Candor Central School District', 'http://www.candor.org/'],
['Canisteo-Greenwood Central School District', 'http://www.canisteo.wnyric.org/'],
['Canton Central School District', 'http://www.ccsdk12.org'],
['Carle Place Union Free School District', 'http://carle.ny.schoolwebpages.com/'],
['Carmel Central School District', 'http://www.ccsd.k12.ny.us/'],
['Carthage Central School District', 'http://www.carthagecsd.org/'],
['Cazenovia Central School District', 'http://www.caz.cnyric.org/'],
['Central Islip Union Free School District', 'http://www.centralislip.k12.ny.us/'],
['Chappaqua Central School District', 'http://www.chappaqua.k12.ny.us/'],
['Chateaugay Central School District', 'http://www.chateaugay.org/'],
['Cheektowaga Central School District', 'http://www.cheektowagacentral.org'],
['Cheektowaga-Maryvale Union Free School District', 'http://www.maryvale.wnyric.org'],
['Chenango Valley Central School District', 'http://www.cvcsd.stier.org'],
['Chester Union Free School District', 'http://chester.ny.schoolwebpages.com/education/school/school.php?sectionid=2'],
['Chittenango Central School District', 'http://www.chittenangoschools.org/'],
['Clifton-Fine Central School District', 'http://www.cfeagles.org'],
['Clymer Central School District', 'http://www.clymer.wnyric.org'],
['Cobleskill-Richmondville Central School District', 'http://www.crcs.k12.ny.us/'],
['Colton-Pierrepont Central School District', 'http://www.cpcs.k12.ny.us'],
['Connetquot Central School District', 'http://www.connetquot.k12.ny.us/'],
['Cooperstown Central School District', 'http://www.cooperstowncs.org/', 'http://www.owncs.org/about/employment', 'https://www.cooperstowncs.org/o/cooperstown-csd/page/employment-information--13'],
['Copenhagen Central School District', 'http://www.ccsknights.org/ccsknights/site/default.asp'],
['Coxsackie-Athens Central School District', 'https://www.cacsd.org/', 'https://www.cacsd.org/domain/188'],
['Croton-Harmon Union Free School District', 'http://www.croton-harmonschools.org/'],
['De Ruyter Central School District', '_ERROR._url_not_found'],
['Delhi Central School District', 'http://www.delhischools.org'],
['Depew Union Free School District', 'http://www.depewschools.org'],
['Deposit Central School District', 'http://www.depositcsd.org'],
['Dolgeville Central School District', 'http://www.dolgeville.org/'],
['Dryden Central School District', 'http://www.dryden.k12.ny.us/'],
['Duanesburg Central School District', 'http://dcs.neric.org/'],
['Dunkirk City School District', 'http://www.dunkirkcsd.org'],
['East Aurora Union Free School District', 'http://www.eaur.wnyric.org'],
['East Greenbush Central School District', 'http://www.egcsd.org/'],
['East Hampton Union Free School District', 'http://www.easthampton.k12.ny.us/'],
['East Irondequoit Central School District', 'http://eicsd.k12.ny.us/'],
['East Quogue Union Free School District', 'http://www.eastquogue.k12.ny.us/'],
['East Ramapo Central School District (Spring Valley)', 'http://www.eram.k12.ny.us'],
['East Rochester Union Free School District', 'http://www.erschools.org/'],
['Eastchester Union Free School District', 'http://www.eastchester.k12.ny.us/'],
['Ellenville Central School District', 'http://www.ecs.k12.ny.us/'],
['Ellicottville Central School District', 'http://www.ellicottvillecentral.com'],
['Elmira City School District', 'http://www.elmiracityschools.com'],
['Elmira Heights Central School District', 'http://www.heightsschools.com'],
['Elmont Union Free School District', 'http://www.elmontschools.org/', 'http://www.elmontschools.org/Page/381', 'https://www.ntschools.org//site/Default.aspx?PageID=5052'],
['Elmsford Union Free School District', 'https://www.eufsd.org/', 'https://www.eufsd.org/domain/119'],
['Fallsburg Central School District', 'http://www.fallsburgcsd.net/'],
['Fillmore Central School District', 'https://www.fillmorecsd.org/', 'https://www.fillmorecsd.org/domain/209'],
['Fishers Island Union Free School District', 'http://www.fischool.com/'],
['Fort Edward Union Free School District', 'http://www.fortedward.org/'],
['Franklin Square Union Free School District', 'http://franklinsquare.k12.ny.us/'],
['Franklinville Central School District', 'http://www.tbafcs.org'],
['Galway Central School District', 'http://www.galwaycsd.org/'],
['Genesee Valley Central School District', 'http://www.gvcs.wnyric.org'],
['George Junior Republic Union Free School District', 'http://www.gjrufsd.org/', 'http://www.gjrufsd.org/careers/'],
['Georgetown-South Otselic Central School District', 'http://www.ovcs.org'],
['Germantown Central School District', 'https://www.germantowncsd.org/', 'https://www.germantowncsd.org/Page/71'],
['Glens Falls City School District', 'http://www.gfsd.org/'],
['Glens Falls Common School District', '_DUP._http://www.gfsd.org/'],
['Gorham-Middlesex Central School District', '_ERROR._url_not_found'],
['Gouverneur Central School District', 'http://gcs.neric.org/'],
['Greece Central School District', 'http://web001.greece.k12.ny.us'],
['Green Island Union Free School District', 'http://www.greenisland.org/'],
['Greenburgh Central School District', 'http://www.greenburgh.k12.ny.us/'],
['Greenburgh Eleven Union Free School District', '_ERROR._url_not_found'],
['Greenburgh-Graham Union Free School District', 'http://www.greenburghgraham.org/'],
['Greenburgh-North Castle Union Free School District', '_ERROR._url_not_found'],
['Greene Central School District', 'http://www.greenecsd.org'],
['Greenport Union Free School District', 'http://www.greenport.k12.ny.us/'],
['Greenwood Lake Union Free School District', 'http://gwl.ouboces.org/'],
['Guilderland Central School District', 'http://www.guilderlandschools.org/'],
['Hammond Central School District', 'http://www.hammond.sllboces.org/'],
['Hannibal Central School District', 'http://www.hannibalcsd.org/'],
['Hastings-On-Hudson Union Free School District', 'http://www.hastings.k12.ny.us/'],
['Hauppauge Union Free School District', 'http://www.hauppauge.k12.ny.us/'],
['Heuvelton Central School District', 'http://heuvelton.schoolfusion.us/'],
['Hicksville Union Free School District', 'http://www.hicksvillepublicschools.org/'],
['Hoosick Falls Central School District', 'http://www.hoosick-falls.k12.ny.us'],
['Hopevale Union Free School District', 'http://www.hopevale.com/'],
['Horseheads Central School District', 'http://www.horseheadsdistrict.com'],
['Hudson Falls Central School District', 'http://www.hfcsd.org/'],
['Hunter-Tannersville Central School District', 'http://www.htcsd.org/'],
['Hyde Park Central School District', 'http://www.hydeparkschools.org'],
['Ilion Central School District', 'https://www.cvalleycsd.org/', 'https://www.cvalleycsd.org/human-resources/'],
['Indian Lake Central School District', 'http://www.ilcsd.org/'],
['Inlet Common School District', '_ERROR._url_not_found'],
['Ithaca City School District', 'http://www.icsd.k12.ny.us/'],
['Jamestown City School District', 'http://www.jamestownpublicschools.org'],
['Jasper-Troupsburg Central School District', 'http://www.jt.wnyric.org/'],
['Jericho Union Free School District', 'http://www.bestschools.org/'],
['Johnsburg Central School District', 'http://www.johnsburgcsd.org/'],
['Keene Central School District', 'http://www.kcs.neric.org/'],
['Kenmore-Tonawanda Union Free School District', 'http://www.kenton.k12.ny.us/'],
['Kings Park Central School District', 'http://www.kpcsd.k12.ny.us/'],
['Kingston City School District', 'http://www.kingstoncityschools.org/'],
['Kiryas Joel Village Union Free School District', '_ERROR._url_not_found'],
['Lackawanna City School District', 'http://www.lackawannaschools.org'],
['Lake Pleasant Central School District', 'http://www.lpschool.com/'],
['Lansing Central School District', 'http://www.lansingschools.org/'],
['Lawrence Union Free School District', 'http://www.lawrence.org/'],
['Little Falls City School District', 'http://www.lfcsd.org'],
['Little Flower Union Free School District', 'http://www.littleflower.schoolfusion.us/'],
['Locust Valley Central School District', 'http://www.lvcsd.k12.ny.us/', 'http://www.vcsd.k12.ny.us/Page/114', 'https://www.pnwboces.org/olas/#!/default?ReturnUrl=%2Fteacherapplication%2F'],
['Longwood Central School District', 'http://www.longwood.k12.ny.us/'],
['Lowville Acad & Central School District', 'http://www.lacs-ny.org'],
['Lynbrook Union Free School District', 'http://www.lynbrook.k12.ny.us'],
['Lyncourt Union Free School District', 'http://www.edline.net/pages/Lyncourt_School'],
['Lyndonville Central School District', 'http://www.lyndonvillecsd.org/'],
['Madison Central School District', 'http://madison.k12.sd.us/'],
['Madrid-Waddington Central School District', 'http://www.mwcsk12.org/'],
['Malone Central School District', 'http://www.malone.k12.ny.us/'],
['Manhasset Union Free School District', 'https://www.manhassetschools.org/', 'https://www.manhassetschools.org/Domain/64'],
['Maplewood Common School District', 'http://www.maplewoodschool.org/', '_CLOSED'],
['Mattituck-Cutchogue Union Free School District', 'http://www.mufsd.com/'],
['Mayfield Central School District', 'http://www.mayfieldk12.com/'],
['Menands Union Free School District', 'http://www.menandsschool.nycap.rr.com/'],
['Merrick Union Free School District', 'http://www.merrick-k6.org/'],
['Middleburgh Central School District', 'http://www.middleburgh.k12.ny.us/'],
['Middletown City School District', 'http://www.middletowncityschools.org'],
['Milford Central School District', 'http://www.schoolworld.milfordcentral.org/'],
['Minerva Central School District', 'http://www.minervasd.org/minervasd/site/default.asp'],
['Mohawk Central School District', 'http://www.mohawk.k12.ny.us/'],
['Morris Central School District', 'http://www.morriscs.org/'],
['Morristown Central School District', 'http://mcsd.schoolfusion.us/'],
['Mount Pleasant Cottage School District', 'http://www.mpcsny.org'],
['Mt Morris Central School District', 'http://www.mtmorriscsd.org/'],
['Mt Pleasant Central School District', 'http://www.mtplcsd.org'],
['Mt Pleasant-Blythedale Union Free School District', 'http://www.mpbschools.org/'],
['NYC Alternative High School District', '_ERROR._url_not_found'],
['NYC Special Schools - District 75', 'http://schools.nycenet.edu/d75/default.htm'],
['Nanuet Union Free School District', 'http://nanunet.lhric.org/'],
['Naples Central School District', 'http://www.naples.k12.ny.us/'],
['New Suffolk Common School District', 'http://newsuffolkschool.com'],
['New York City District  #15', '_ERROR._url_not_found'],
['New York City District # 1', '_DUP._http://www.newyorkschools.com'],
['New York City District # 2', '_ERROR._url_not_found'],
['New York City District # 3', '_ERROR._url_not_found'],
['New York City District # 4', '_ERROR._url_not_found'],
['New York City District # 5', '_ERROR._url_not_found'],
['New York City District # 6', '_ERROR._url_not_found'],
['New York City District #7', '_ERROR'],
['New York City District # 8', '_ERROR._url_not_found'],
['New York City District # 9', '_ERROR._url_not_found'],
['New York City District #10', '_ERROR._url_not_found'],
['New York City District #11', '_ERROR._url_not_found'],
['New York City District #12', '_ERROR'],
['New York City District #13', '_ERROR._url_not_found'],
['New York City District #14', '_ERROR._url_not_found'],
['New York City District #16', '_ERROR._url_not_found'],
['New York City District #17', '_ERROR._url_not_found'],
['New York City District #18', '_ERROR._url_not_found'],
['New York City District #19', '_ERROR'],
['New York City District #20', '_ERROR._url_not_found'],
['New York City District #21', '_ERROR._url_not_found'],
['New York City District #22', '_ERROR._url_not_found'],
['New York City District #23', '_ERROR._url_not_found'],
['New York City District #24', '_ERROR._url_not_found'],
['New York City District #25', '_ERROR._url_not_found'],
['New York City District #26', '_ERROR._url_not_found'],
['New York City District #27', '_ERROR._url_not_found'],
['New York City District #28', '_ERROR._url_not_found'],
['New York City District #29', '_ERROR._url_not_found'],
['New York City District #30', '_ERROR._url_not_found'],
['New York City District #32', '_ERROR'],
['Newark Central School District', 'http://www.newark.k12.ny.us/'],
['Newark Valley Central School District', 'http://nvcs.stier.org/'],
['Newcomb Central School District', 'http://www.newcombcsd.org/education/district/district.php?sectionid=1', 'https://bcsd.recruitfront.com/JobOpportunities.aspx', 'https://plus.google.com/s/%23Employment/posts'],
['Newfield Central School District', 'http://www.newfieldschools.org/'],
['Niagara-Wheatfield Central School District', 'https://www.nwcsd.org/', 'https://www.nwcsd.org/Page/64'],
['Niskayuna Central School District', 'http://www.niskyschools.org/'],
['North Greenbush Common School District', '_ERROR._url_not_found'],
['North Merrick Union Free School District', 'http://www.nmerrickschools.org/'],
['North Syracuse Central School District', 'http://www.nscsd.org/'],
['North Tonawanda City School District', 'http://www.ntschools.org/ntschools/site/default.asp'],
['Northeastern Clinton Central School District', 'https://www.nccscougar.org/', 'https://www.nccscougar.org/domain/20'],
['Northville Central School District', 'http://northvillecsd.k12.ny.us/'],
['Norwich City School District', 'http://www.norwichcityschooldistrict.com'],
['Nyack Union Free School District', 'http://www.nyackschools.com/'],
['Oakfield-Alabama Central School District', 'https://www.oahornets.org/', 'https://www.oahornets.org/apps/jobs/'],
['Oceanside Union Free School District', 'http://www.oceanside.k12.ny.us/'],
['Oneida City School District', 'http://www.oneidacsd.org/'],
['Onteora Central School District', 'http://www.onteora.k12.ny.us/'],
['Oppenheim-Ephratah Central School District', 'http://www.oecs.k12.ny.us'],
['Ossining Union Free School District', 'http://www.ossiningufsd.org/', 'http://gufsd.org/district/employment-opportunities', 'https://ossiningufsd.org/departments/human-resources'],
['Otego-Unadilla Central School District', 'http://www.unatego.org'],
['Oysterponds Union Free School District', 'http://www.oysterponds.k12.ny.us/'],
['Parishville-Hopkinton Central School District', 'http://phcs.neric.org/'],
['Patchogue-Medford Union Free School District', 'http://www.pat-med.k12.ny.us/'],
['Pavilion Central School District', 'http://www.pavilioncsd.org/'],
['Pawling Central School District', 'http://www.pawlingschools.org'],
['Pearl River Union Free School District', 'http://www.pearlriver.k12.ny.us/'],
['Pelham Union Free School District', 'http://www.pelhamschools.org/'],
['Pembroke Central School District', 'http://www.pembroke.k12.ny.us/'],
['Phoenix Central School District', 'http://www.phoenix.k12.ny.us/'],
['Piseco Common School District', '_ERROR._url_not_found'],
['Plainview-Old Bethpage Central School District', 'http://www.pob.k12.ny.us/'],
['Plattsburgh City School District', 'http://plattsburgh.neric.org'],
['Pleasantville Union Free School District', 'http://www2.lhric.org/pleasantville/'],
['Poland Central School District', 'https://www.polandcs.org/', 'https://www.polandcs.org/domain/270'],
['Port Byron Central School District', 'http://portbyron.cnyric.org/'],
['Port Jefferson Union Free School District', 'http://portjefferson.ny.schoolwebpages.com/'],
['Portville Central School District', 'http://www.portville.wnyric.org'],
['Prattsburgh Central School District', 'https://www.prattsburghcsd.org/', 'https://www.prattsburghcsd.org/Page/26'],
['Putnam Central School District', 'http://putnamcs.neric.org/'],
['Quogue Union Free School District', 'http://www.quogue.k12.ny.us/'],
['Ramapo Central School District (Suffern)', 'http://www.ramapocentral.org/'],
['Randolph Academy UFSD', 'http://www.randolphacademy.org'],
['Randolph Central School District', 'http://www.randolphcsd.org', 'http://www.randolphcsd.org/domain/24', 'https://www.phcsd.org/apps/pages/index.jsp?uREC_ID=1161786&type=d&pREC_ID=1415161'],
['Raquette Lake Union Free School District', 'http://www.fehb.org/raquette.htm'],
['Ravena-Coeymans-Selkirk Central School District', 'http://www.rcscsd.org/', 'https://cscsd.recruitfront.com/JobOpportunities', 'https://www.scsd.org/employment', 'https://www.rcscsd.org/about-us/employment'],
['Red Hook Central School District', 'http://www.redhookcentralschools.org'],
['Remsenburg-Speonk Union Free School District', 'http://rsufsd.wordpress.com/'],
['Ripley Central School District', 'http://ripleycsd.wnyric.org'],
['Rocky Point Union Free School District', 'http://www.rockypointschools.org/'],
['Rome City School District', 'http://www.romecsd.org/'],
['Romulus Central School District', 'http://www.rcs.k12.ny.us/'],
['Rondout Valley Central School District', 'http://www.rondout.k12.ny.us/'],
['Roosevelt Union Free School District', 'http://www.rooseveltufsd.com/'],
['Roxbury Central School District', 'http://www.roxburycs.org'],
['Rush-Henrietta Central School District', 'http://www.rhnet.org/'],
['Rye City School District', 'http://www.ryecityschools.lhric.org/'],
['Rye Neck Union Free School District', 'http://www.ryeneck.k12.ny.us/default.aspx'],
['Sachem Central School District', 'http://www.sachem.edu/'],
['Sag Harbor Union Free School District', 'http://www.sagharbor.k12.ny.us/'],
['Sagaponack Common School District', 'http://www.sagaponackschool.com/'],
['Salamanca City School District', 'http://www.salamancany.org'],
['Salem Central School District', 'http://www.salemcsd.org/'],
['Salmon River Central School District', 'http://www.srk12.org/'],
['Sandy Creek Central School District', 'http://www.sccs.cnyric.org/'],
['Saranac Central School District', 'http://www.saranac.org'],
['Saugerties Central School District', 'http://saugerties.schoolwires.com/'],
['Sayville Union Free School District', 'http://www.sayville.k12.ny.us/'],
['Schalmont Central School District', 'http://www.schalmont.org/'],
['Schenectady City School District', 'http://www.schenectady.k12.ny.us/'],
['Schenevus Central School District', 'https://www.schenevuscsd.org/', 'https://www.schenevuscsd.org/EmploymentOpportunities.aspx'],
['Schoharie Central School District', 'http://www.schoharie.k12.ny.us/'],
['Scotia-Glenville Central School District', 'http://www.sgcsd.neric.org/'],
['Shelter Island Union Free School District', 'http://sischool.dev6.hamptons.com/'],
['Sherman Central School District', 'http://shermancsd.org/', 'http://shermancsd.org/employment/'],
['Silver Creek Central School District', 'http://www.silvercreek.wnyric.org'],
['Somers Central School District', 'http://https://www.edline.net/pages/Somers_CSD'],
['South Huntington Union Free School District', 'http://www.shuntington.k12.ny.us/'],
['South Orangetown Central School District', 'http://www.socsd.k12.ny.us/'],
['Southern Cayuga Central School District', 'http://www.southerncayuga.org'],
['Southold Union Free School District', 'http://www.southoldufsd.net/'],
['Spencer-Van Etten Central School District', 'http://www.svecsd.org/'],
['Springs Union Free School District', 'http://www.springs.k12.ny.us/'],
['St Johnsville Central School District', 'http://sjcsd.org/'],
['St Regis Falls Central School District', 'http://stregisfallscsd.org/'],
['Staten Island Schools - NYC District #31', '_ERROR._url_not_found'],
['Stillwater Central School District', 'http://www.scsd.org/'],
['Stockbridge Valley Central School District', 'http://www.stockbridgevalley.org/'],
['Sullivan West Central School District', 'http://www.swcsd.org/', 'http://www.swcsd.org/Page/194', 'http://www.wcsd.org/district/employment_opportunities'],
['Sweet Home Central School District', 'http://www.shs.k12.ny.us/'],
['Thousand Islands Central School District', 'http://www.1000islandsschools.org'],
['Tioga Central School District', 'http://www.tcsaa.org/'],
['Tri-Valley Central School District', 'http://tvcs.k12.ny.us/'],
['Troy City School District', 'http://www.troy.k12.ny.us/'],
['Trumansburg Central School District', 'http://www.tburg.k12.ny.us/'],
['Tuckahoe Common School District', 'http://www.tuckahoe.k12.ny.us/'],
['Tupper Lake Central School District', 'http://www.tupperlakecsd.net/'],
['Tuxedo Union Free School District', 'http://www.tuxedoufsd.org/', 'http://www.tuxedoufsd.org/district_services/business_office/employment_opportunities'],
['Union Springs Central School District', 'http://www.unionspringscsd.org/', 'http://www.unionspringscsd.org/districtpage.cfm?pageid=193'],
['Union-Endicott Central School District', 'https://www.uek12.org/', 'https://www.uek12.org/Employment.aspx'],
['Valhalla Union Free School', 'http://www.valhalla.k12.ny.us/'],
['Valley Central School District', 'http://www.vcsd.k12.ny.us/valleycentralsd/site/default.asp'],
['Van Hornesville-Owen D. Young Central School District', '_ERROR._url_not_found'],
['Vestal Central School District', 'http://www.vestal.k12.ny.us'],
['Voorheesville Central School District', 'http://vcsdk12.org/'],
['Wainscott Common School District', 'http://www.wainscottschool.com/'],
['Walton Central School District', 'http://www.waltoncsd.stier.org'],
['Wantagh Union Free School District', 'http://www.wms.wantaghufsd.k12.ny.us/'],
['Wappingers Central School District', '_ERROR._url_not_found'],
['Warrensburg Central School District', 'http://www.wcsd.org/'],
['Waterford-Halfmoon Union Free School District', 'http://www.whufsd.org'],
['Waterville Central School District', 'http://www.watervilleschools.org/'],
['Watervliet City School District', 'http://www.watervlietcityschools.org/'],
['Watkins Glen Central School District', 'http://www.watkinsglenschools.com/'],
['Wayland-Cohocton Central School District', 'http://www.wccsk12.org/'],
['Wayne Central School District', 'http://wayne.k12.ny.us/'],
['Webster Central School District', 'http://www.websterschools.org'],
['Weedsport Central School District', 'http://www.weedsport.org'],
['Wells Central School District', 'http://www.wellscsd.com/main/'],
['West Babylon Union Free School District', 'http://www.westbabylon.k12.ny.us/'],
['West Irondequoit Central School District', 'http://www.westirondequoit.org/'],
['West Park Union Free School District', '_ERROR._url_not_found'],
['Westbury Union Free School District', 'http://www.westburyschools.org/'],
['Wheelerville Union Free School District', 'http://www.wufselementary.k12.ny.us/'],
['White Plains City School District', 'https://www.whiteplainspublicschools.org/', 'https://www.whiteplainspublicschools.org/Page/546'],
['Wyoming Central School District', 'http://www.wyoming.k12.ny.us/'],
['Yorkshire-Pioneer Central School District', 'http://www.pioneerschools.org', 'http://www.erschools.org/departments/employment/employment_opportunities', 'http://www.pioneerschools.org/domain/48'],
['Yorktown Central School District', 'http://www.yorktowncsd.org/']
]














for i in g:

    for ii in new:
        
        if ii [0] in i[1]:
    
            #print('\n\nMatch:', i, '\n', ii)
            
            i.append(ii[0])


for i in g:
    print(i)



print('\n\n\n\nErrors:')
for i in g:
    if len(i) != 3:
        print(i)













