

grudb_list = [
['Green Island Union Free School District', 'http://www.greenisland.org/'],
['Guilderland Central School District', 'http://www.guilderlandschools.org/'],
['Maplewood Common School District', 'http://www.maplewoodschool.org/'],
['Menands Union Free School District', 'http://www.menandsschool.nycap.rr.com/'],
['Ravena-Coeymans-Selkirk Central School District', 'http://www.rcscsd.org/', 'https://cscsd.recruitfront.com/JobOpportunities', 'https://www.scsd.org/employment', 'https://www.rcscsd.org/about-us/employment'],
['Voorheesville Central School District', 'http://vcsdk12.org/'],
['Watervliet City School District', 'http://www.watervlietcityschools.org/'],
['Alfred-Almond Central School District', 'http://www.aacs.wnyric.org/'],
['Fillmore Central School District', 'http://www.fillmore.wnyric.org'],
['Genesee Valley Central School District', 'http://www.gvcs.wnyric.org'],
['New York City District # 7', 'http://www.schooldigger.com'],
['New York City District # 8', '_ERROR._url_not_found'],
['New York City District # 9', '_ERROR._url_not_found'],
['New York City District #10', '_ERROR._url_not_found'],
['New York City District #11', '_ERROR._url_not_found'],
['New York City District #12', 'http://www.newyorkschools.com/districts/nyc-district-12.html'],
['Binghamton School District', 'http://www.binghamtonschools.org'],
['Chenango Valley Central School District', 'http://www.cvcsd.stier.org'],
['Deposit Central School District', 'http://www.depositcsd.org'],
['Union-Endicott Central School District', 'http://www.uetigers.stier.org'],
['Vestal Central School District', 'http://www.vestal.k12.ny.us'],
['Allegany - Limestone Central School District', 'http://www.alli.wnyric.org'],
['Ellicottville Central School District', 'http://www.ellicottvillecentral.com'],
['Franklinville Central School District', 'http://www.tbafcs.org'],
['Portville Central School District', 'http://www.portville.wnyric.org'],
['Randolph Academy UFSD', 'http://www.randolphacademy.org'],
['Randolph Central School District', 'http://www.randolphcsd.org', 'http://www.randolphcsd.org/domain/24', 'https://www.phcsd.org/apps/pages/index.jsp?uREC_ID=1161786&type=d&pREC_ID=1415161'],
['Salamanca City School District', 'http://www.salamancany.org'],
['Yorkshire-Pioneer Central School District', 'http://www.pioneerschools.org', 'http://www.erschools.org/departments/employment/employment_opportunities', 'http://www.pioneerschools.org/domain/48'],
['Auburn City School District', 'http://district.auburn.cnyric.org'],
['Port Byron Central School District', 'http://portbyron.cnyric.org/'],
['Southern Cayuga Central School District', 'http://www.southerncayuga.org'],
['Union Springs Central School District', 'http://www.uscsd.info'],
['Weedsport Central School District', 'http://www.weedsport.org'],
['Bemus Point Central School District', 'http://www.mghs.org'],
['Clymer Central School District', 'http://www.clymer.wnyric.org'],
['Dunkirk City School District', 'http://www.dunkirkcsd.org'],
['Jamestown City School District', 'http://www.jamestownpublicschools.org'],
['Ripley Central School District', 'http://ripleycsd.wnyric.org'],
['Sherman Central School District', 'http://www.sherman.wnyric.org/'],
['Silver Creek Central School District', 'http://www.silvercreek.wnyric.org'],
['Elmira City School District', 'http://www.elmiracityschools.com'],
['Elmira Heights Central School District', 'http://www.heightsschools.com'],
['Horseheads Central School District', 'http://www.horseheadsdistrict.com'],
['Georgetown-South Otselic Central School District', 'http://www.ovcs.org'],
['Greene Central School District', 'http://www.greenecsd.org'],
['Norwich City School District', 'http://www.norwichcityschooldistrict.com'],
['Beekmantown Central School District', 'http://www.bcsdk12.org'],
['Northeastern Clinton Central School District', 'http://www.nccscougars.org'],
['Plattsburgh City School District', 'http://plattsburgh.neric.org'],
['Saranac Central School District', 'http://www.saranac.org'],
['Berkshire Union Free School District', 'http://www.berkshirefarm.org'],
['Germantown Central School District', 'http://www.germantownny.org/'],
['Delhi Central School District', 'http://www.delhischools.org'],
['Roxbury Central School District', 'http://www.roxburycs.org'],
['Walton Central School District', 'http://www.waltoncsd.stier.org'],
['Hyde Park Central School District', 'http://www.hydeparkschools.org'],
['Pawling Central School District', 'http://www.pawlingschools.org'],
['Red Hook Central School District', 'http://www.redhookcentralschools.org'],
['Wappingers Central School District', '_ERROR._url_not_found'],
['Cheektowaga Central School District', 'http://www.cheektowagacentral.org'],
['Cheektowaga-Maryvale Union Free School District', 'http://www.maryvale.wnyric.org'],
['Depew Union Free School District', 'http://www.depewschools.org'],
['East Aurora Union Free School District', 'http://www.eaur.wnyric.org'],
['Hopevale Union Free School District', 'http://www.hopevale.com/'],
['Kenmore-Tonawanda Union Free School District', 'http://www.kenton.k12.ny.us/'],
['Lackawanna City School District', 'http://www.lackawannaschools.org'],
['Sweet Home Central School District', 'http://www.shs.k12.ny.us/'],
['Keene Central School District', 'http://www.kcs.neric.org/'],
['Minerva Central School District', 'http://www.minervasd.org/minervasd/site/default.asp'],
['Newcomb Central School District', 'http://www.newcombcsd.org/education/district/district.php?sectionid=1', 'https://bcsd.recruitfront.com/JobOpportunities.aspx', 'https://plus.google.com/s/%23Employment/posts'],
['Brushton-Moira Central School District', 'http://www.fehb.org'],
['Chateaugay Central School District', 'http://www.chateaugay.org/'],
['Malone Central School District', 'http://www.malone.k12.ny.us/'],
['Salmon River Central School District', 'http://www.srk12.org/'],
['St Regis Falls Central School District', 'http://stregisfallscsd.org/'],
['Tupper Lake Central School District', 'http://www.tupperlakecsd.net/'],
['Mayfield Central School District', 'http://www.mayfieldk12.com/'],
['Northville Central School District', 'http://northvillecsd.k12.ny.us/'],
['Oppenheim-Ephratah Central School District', 'http://www.oecs.k12.ny.us'],
['Wheelerville Union Free School District', 'http://www.wufselementary.k12.ny.us/'],
['Oakfield-Alabama Central School District', 'http://www.oacs.k12.ny.us/'],
['Pavilion Central School District', 'http://www.pavilioncsd.org/'],
['Pembroke Central School District', 'http://www.pembroke.k12.ny.us/'],
['Coxsackie-Athens Central School District', 'http://www.coxsackie-athens.org/'],
['Hunter-Tannersville Central School District', 'http://www.htcsd.org/'],
['Indian Lake Central School District', 'http://www.ilcsd.org/'],
['Inlet Common School District', '_ERROR._url_not_found'],
['Lake Pleasant Central School District', 'http://www.lpschool.com/'],
['Piseco Common School District', '_ERROR._url_not_found'],
['Raquette Lake Union Free School District', 'http://www.fehb.org/raquette.htm'],
['Wells Central School District', 'http://www.wellscsd.com/main/'],
['Bridgewater-West Winfield Central School District', 'http://www.mmcsd.org/'],
['Dolgeville Central School District', 'http://www.dolgeville.org/'],
['Ilion Central School District', 'http://www.ilioncsd.org/'],
['Little Falls City School District', 'http://www.lfcsd.org'],
['Mohawk Central School District', 'http://www.mohawk.k12.ny.us/'],
['Poland Central School District', 'http://www.polandcs.com'],
['Van Hornesville-Owen D. Young Central School District', '_ERROR._url_not_found'],
['Carthage Central School District', 'http://www.carthagecsd.org/'],
['Thousand Islands Central School District', 'http://www.1000islandsschools.org'],
['New York City District  #15', '_ERROR._url_not_found'],
['New York City District #13', '_ERROR._url_not_found'],
['New York City District #14', '_ERROR._url_not_found'],
['New York City District #16', '_ERROR._url_not_found'],
['New York City District #17', '_ERROR._url_not_found'],
['New York City District #18', '_ERROR._url_not_found'],
['New York City District #19', 'http://www.newyorkschools.com'],
['New York City District #20', '_ERROR._url_not_found'],
['New York City District #21', '_ERROR._url_not_found'],
['New York City District #22', '_ERROR._url_not_found'],
['New York City District #23', '_ERROR._url_not_found'],
['New York City District #32', 'http://www.newyorkschools.com/districts/nyc-district-32.html'],
['Beaver River Central School District', 'http://www.brcsd.org'],
['Copenhagen Central School District', 'http://www.ccsknights.org/ccsknights/site/default.asp'],
['Lowville Acad & Central School District', 'http://www.lacs-ny.org'],
['Mt Morris Central School District', 'http://www.mtmorriscsd.org/'],
['Brookfield Central School District', 'http://www.bcsbeavers.org'],
['Canastota Central School District', 'http://www.canastotacsd.org'],
['Cazenovia Central School District', 'http://www.caz.cnyric.org/'],
['Chittenango Central School District', 'http://www.chittenangoschools.org/'],
['De Ruyter Central School District', '_ERROR._url_not_found'],
['Madison Central School District', 'http://madison.k12.sd.us/'],
['Oneida City School District', 'http://www.oneidacsd.org/'],
['Stockbridge Valley Central School District', 'http://www.stockbridgevalley.org/'],
['Brighton Central School District', 'http://www.bcsd.org'],
['Brockport Central School District', 'http://www.brockport.k12.ny.us/'],
['East Irondequoit Central School District', 'http://eicsd.k12.ny.us/'],
['East Rochester Union Free School District', 'http://www.erschools.org/'],
['Greece Central School District', 'http://web001.greece.k12.ny.us'],
['Rush-Henrietta Central School District', 'http://www.rhnet.org/'],
['Webster Central School District', 'http://www.websterschools.org'],
['West Irondequoit Central School District', 'http://www.westirondequoit.org/'],
['St Johnsville Central School District', 'http://sjcsd.org/'],
['Baldwin Union Free School District', 'http://www.baldwin.k12.ny.us/'],
['Bellmore Union Free School District', 'http://www.bellmore.k12.ny.us'],
['Bellmore-Merrick Central High School District', 'http://www.bellmore-merrick.k12.ny.us/', 'http://www.bellmore-merrick.k12.ny.us/district/opportunities', 'http://www.merrick.k12.ny.us/district/job_opportunities'],
['Carle Place Union Free School District', 'http://carle.ny.schoolwebpages.com/'],
['Elmont Union Free School District', 'http://www.elmontschools.org/', 'http://www.elmontschools.org/Page/381', 'https://www.ntschools.org//site/Default.aspx?PageID=5052'],
['Franklin Square Union Free School District', 'http://franklinsquare.k12.ny.us/'],
['Hicksville Union Free School District', 'http://www.hicksvillepublicschools.org/'],
['Jericho Union Free School District', 'http://www.bestschools.org/'],
['Lawrence Union Free School District', 'http://www.lawrence.org/'],
['Locust Valley Central School District', 'http://www.lvcsd.k12.ny.us/', 'http://www.vcsd.k12.ny.us/Page/114', 'https://www.pnwboces.org/olas/#!/default?ReturnUrl=%2Fteacherapplication%2F'],
['Lynbrook Union Free School District', 'http://www.lynbrook.k12.ny.us'],
['Manhasset Union Free School District', 'http://www.manhasset.k12.ny.us/'],
['Merrick Union Free School District', 'http://www.merrick-k6.org/'],
['North Merrick Union Free School District', 'http://www.nmerrickschools.org/'],
['Oceanside Union Free School District', 'http://www.oceanside.k12.ny.us/'],
['Plainview-Old Bethpage Central School District', 'http://www.pob.k12.ny.us/'],
['Roosevelt Union Free School District', 'http://www.rooseveltufsd.com/'],
['Wantagh Union Free School District', 'http://www.wms.wantaghufsd.k12.ny.us/'],
['Westbury Union Free School District', 'http://www.westburyschools.org/'],
['New York City District # 1', '_DUP._http://www.newyorkschools.com'],
['New York City District # 2', '_ERROR._url_not_found'],
['New York City District # 3', '_ERROR._url_not_found'],
['New York City District # 4', '_ERROR._url_not_found'],
['New York City District # 5', '_ERROR._url_not_found'],
['New York City District # 6', '_ERROR._url_not_found'],
['NYC Alternative High School District', '_ERROR._url_not_found'],
['NYC Special Schools - District 75', 'http://schools.nycenet.edu/d75/default.htm'],
['Niagara-Wheatfield Central School District', 'http://www.livestrong.com'],
['North Tonawanda City School District', 'http://www.ntschools.org/ntschools/site/default.asp'],
['Rome City School District', 'http://www.romecsd.org/'],
['Waterville Central School District', 'http://www.watervilleschools.org/'],
['Lyncourt Union Free School District', 'http://www.edline.net/pages/Lyncourt_School'],
['North Syracuse Central School District', 'http://www.nscsd.org/'],
['Gorham-Middlesex Central School District', '_ERROR._url_not_found'],
['Naples Central School District', 'http://www.naples.k12.ny.us/'],
['Chester Union Free School District', 'http://chester.ny.schoolwebpages.com/education/school/school.php?sectionid=2'],
['Greenwood Lake Union Free School District', 'http://gwl.ouboces.org/'],
['Kiryas Joel Village Union Free School District', '_ERROR._url_not_found'],
['Middletown City School District', 'http://www.middletowncityschools.org'],
['Tuxedo Union Free School District', 'http://www.tuxedoschooldistrict.com/'],
['Valley Central School District', 'http://www.vcsd.k12.ny.us/valleycentralsd/site/default.asp'],
['Lyndonville Central School District', 'http://www.lyndonvillecsd.org/'],
['Hannibal Central School District', 'http://www.hannibalcsd.org/'],
['Phoenix Central School District', 'http://www.phoenix.k12.ny.us/'],
['Sandy Creek Central School District', 'http://www.sccs.cnyric.org/'],
['Cooperstown Central School District', 'http://www.cooperstowncs.org/', 'http://www.owncs.org/about/employment', 'https://www.cooperstowncs.org/o/cooperstown-csd/page/employment-information--13'],
['Milford Central School District', 'http://www.schoolworld.milfordcentral.org/'],
['Morris Central School District', 'http://www.morriscs.org/'],
['Otego-Unadilla Central School District', 'http://www.unatego.org'],
['Schenevus Central School District', 'http://www.schenevuscs.org/'],
['Carmel Central School District', 'http://www.ccsd.k12.ny.us/'],
['New York City District #24', '_ERROR._url_not_found'],
['New York City District #25', '_ERROR._url_not_found'],
['New York City District #26', '_ERROR._url_not_found'],
['New York City District #27', '_ERROR._url_not_found'],
['New York City District #28', '_ERROR._url_not_found'],
['New York City District #29', '_ERROR._url_not_found'],
['New York City District #30', '_ERROR._url_not_found'],
['Brunswick Central School District', 'http://www.brittonkill.k12.ny.us'],
['East Greenbush Central School District', 'http://www.egcsd.org/'],
['Hoosick Falls Central School District', 'http://www.hoosick-falls.k12.ny.us'],
['North Greenbush Common School District', '_ERROR._url_not_found'],
['Troy City School District', 'http://www.troy.k12.ny.us/'],
['Staten Island Schools - NYC District #31', '_ERROR._url_not_found'],
['East Ramapo Central School District (Spring Valley)', 'http://www.eram.k12.ny.us'],
['Nanuet Union Free School District', 'http://nanunet.lhric.org/'],
['Nyack Union Free School District', 'http://www.nyackschools.com/'],
['Pearl River Union Free School District', 'http://www.pearlriver.k12.ny.us/'],
['Ramapo Central School District (Suffern)', 'http://www.ramapocentral.org/'],
['South Orangetown Central School District', 'http://www.socsd.k12.ny.us/'],
['Ballston Spa Central School District', 'http://www.ballstonspa.k12.ny.us/'],
['Burnt Hills-Ballston Lake Central School District', 'http://www.bhbl.org/'],
['Galway Central School District', 'http://www.galwaycsd.org/'],
['Stillwater Central School District', 'http://www.scsd.org/'],
['Waterford-Halfmoon Union Free School District', 'http://www.whufsd.org'],
['Duanesburg Central School District', 'http://dcs.neric.org/'],
['Niskayuna Central School District', 'http://www.niskyschools.org/'],
['Schalmont Central School District', 'http://www.schalmont.org/'],
['Schenectady City School District', 'http://www.schenectady.k12.ny.us/'],
['Scotia-Glenville Central School District', 'http://www.sgcsd.neric.org/'],
['Cobleskill-Richmondville Central School District', 'http://www.crcs.k12.ny.us/'],
['Middleburgh Central School District', 'http://www.middleburgh.k12.ny.us/'],
['Schoharie Central School District', 'http://www.schoharie.k12.ny.us/'],
['Watkins Glen Central School District', 'http://www.watkinsglenschools.com/'],
['Romulus Central School District', 'http://www.rcs.k12.ny.us/'],
['Canton Central School District', 'http://www.ccsdk12.org'],
['Clifton-Fine Central School District', 'http://www.cfeagles.org'],
['Colton-Pierrepont Central School District', 'http://www.cpcs.k12.ny.us'],
['Gouverneur Central School District', 'http://gcs.neric.org/'],
['Hammond Central School District', 'http://www.hammond.sllboces.org/'],
['Heuvelton Central School District', 'http://heuvelton.schoolfusion.us/'],
['Madrid-Waddington Central School District', 'http://www.mwcsk12.org/'],
['Morristown Central School District', 'http://mcsd.schoolfusion.us/'],
['Parishville-Hopkinton Central School District', 'http://phcs.neric.org/'],
['Arkport Central School District', 'http://acs.stev.net/'],
['Campbell-Savona Central School District', 'http://www.campbellsavona.wnyric.org/'],
['Canisteo-Greenwood Central School District', 'http://www.canisteo.wnyric.org/'],
['Jasper-Troupsburg Central School District', 'http://www.jt.wnyric.org/'],
['Prattsburgh Central School District', 'http://www.prattsburgh.wnyric.org/'],
['Wayland-Cohocton Central School District', 'http://www.wccsk12.org/'],
['Amagansett Union Free School District', 'http://www.amagansettschool.org/'],
['Brentwood Union Free School District', 'http://www.brentwood.k12.ny.us/'],
['Central Islip Union Free School District', 'http://www.centralislip.k12.ny.us/'],
['Connetquot Central School District', 'http://www.connetquot.k12.ny.us/'],
['East Hampton Union Free School District', 'http://www.easthampton.k12.ny.us/'],
['East Quogue Union Free School District', 'http://www.eastquogue.k12.ny.us/'],
['Fishers Island Union Free School District', 'http://www.fischool.com/'],
['Greenport Union Free School District', 'http://www.greenport.k12.ny.us/'],
['Hauppauge Union Free School District', 'http://www.hauppauge.k12.ny.us/'],
['Kings Park Central School District', 'http://www.kpcsd.k12.ny.us/'],
['Little Flower Union Free School District', 'http://www.littleflower.schoolfusion.us/'],
['Longwood Central School District', 'http://www.longwood.k12.ny.us/'],
['Mattituck-Cutchogue Union Free School District', 'http://www.mufsd.com/'],
['New Suffolk Common School District', 'http://newsuffolkschool.com'],
['Oysterponds Union Free School District', 'http://www.oysterponds.k12.ny.us/'],
['Patchogue-Medford Union Free School District', 'http://www.pat-med.k12.ny.us/'],
['Port Jefferson Union Free School District', 'http://portjefferson.ny.schoolwebpages.com/'],
['Quogue Union Free School District', 'http://www.quogue.k12.ny.us/'],
['Remsenburg-Speonk Union Free School District', 'http://rsufsd.wordpress.com/'],
['Rocky Point Union Free School District', 'http://www.rockypointschools.org/'],
['Sachem Central School District', 'http://www.sachem.edu/'],
['Sag Harbor Union Free School District', 'http://www.sagharbor.k12.ny.us/'],
['Sagaponack Common School District', 'http://www.sagaponackschool.com/'],
['Sayville Union Free School District', 'http://www.sayville.k12.ny.us/'],
['Shelter Island Union Free School District', 'http://sischool.dev6.hamptons.com/'],
['South Huntington Union Free School District', 'http://www.shuntington.k12.ny.us/'],
['Southold Union Free School District', 'http://www.southoldufsd.net/'],
['Springs Union Free School District', 'http://www.springs.k12.ny.us/'],
['Tuckahoe Common School District', 'http://www.tuckahoe.k12.ny.us/'],
['Wainscott Common School District', 'http://www.wainscottschool.com/'],
['West Babylon Union Free School District', 'http://www.westbabylon.k12.ny.us/'],
['Fallsburg Central School District', 'http://www.fallsburgcsd.net/'],
['Sullivan West Central School District', 'http://www.swcsd.org/', 'http://www.swcsd.org/Page/194', 'http://www.wcsd.org/district/employment_opportunities'],
['Tri-Valley Central School District', 'http://tvcs.k12.ny.us/'],
['Candor Central School District', 'http://www.candor.org/'],
['Newark Valley Central School District', 'http://nvcs.stier.org/'],
['Spencer-Van Etten Central School District', 'http://www.svecsd.org/'],
['Tioga Central School District', 'http://www.tcsaa.org/'],
['Dryden Central School District', 'http://www.dryden.k12.ny.us/'],
['George Junior Republic Union Free School District', 'http://www.georgejuniorrepublic.com/'],
['Ithaca City School District', 'http://www.icsd.k12.ny.us/'],
['Lansing Central School District', 'http://www.lansingschools.org/'],
['Newfield Central School District', 'http://www.newfieldschools.org/'],
['Trumansburg Central School District', 'http://www.tburg.k12.ny.us/'],
['Ellenville Central School District', 'http://www.ecs.k12.ny.us/'],
['Kingston City School District', 'http://www.kingstoncityschools.org/'],
['Onteora Central School District', 'http://www.onteora.k12.ny.us/'],
['Rondout Valley Central School District', 'http://www.rondout.k12.ny.us/'],
['Saugerties Central School District', 'http://saugerties.schoolwires.com/'],
['West Park Union Free School District', '_ERROR._url_not_found'],
['Bolton Central School District', 'http://www.boltoncsd.org/'],
['Glens Falls City School District', 'http://www.gfsd.org/'],
['Glens Falls Common School District', '_DUP._http://www.gfsd.org/'],
['Johnsburg Central School District', 'http://www.johnsburgcsd.org/'],
['Warrensburg Central School District', 'http://www.wcsd.org/'],
['Fort Edward Union Free School District', 'http://www.fortedward.org/'],
['Hudson Falls Central School District', 'http://www.hfcsd.org/'],
['Putnam Central School District', 'http://putnamcs.neric.org/'],
['Salem Central School District', 'http://www.salemcsd.org/'],
['Newark Central School District', 'http://www.newark.k12.ny.us/'],
['Wayne Central School District', 'http://wayne.k12.ny.us/'],
['Abbott Union Free School District', '_ERROR._url_not_found'],
['Blind Brook-Rye Union Free School District', 'http://www.blindbrook.org/'],
['Bronxville Union Free School District', 'http://www.bronxville.k12.ny.us/'],
['Chappaqua Central School District', 'http://www.chappaqua.k12.ny.us/'],
['Croton-Harmon Union Free School District', 'http://www.croton-harmonschools.org/'],
['Eastchester Union Free School District', 'http://www.eastchester.k12.ny.us/'],
['Elmsford Union Free School District', 'http://www.elmsfordschools.k12.ny.us'],
['Greenburgh Central School District', 'http://www.greenburgh.k12.ny.us/'],
['Greenburgh Eleven Union Free School District', '_ERROR._url_not_found'],
['Greenburgh-Graham Union Free School District', 'http://www.greenburghgraham.org/'],
['Greenburgh-North Castle Union Free School District', '_ERROR._url_not_found'],
['Hastings-On-Hudson Union Free School District', 'http://www.hastings.k12.ny.us/'],
['Mount Pleasant Cottage School District', 'http://www.mpcsny.org'],
['Mt Pleasant Central School District', 'http://www.mtplcsd.org'],
['Mt Pleasant-Blythedale Union Free School District', 'http://www.mpbschools.org/'],
['Ossining Union Free School District', 'http://www.ossiningufsd.org/', 'http://gufsd.org/district/employment-opportunities', 'https://ossiningufsd.org/departments/human-resources'],
['Pelham Union Free School District', 'http://www.pelhamschools.org/'],
['Pleasantville Union Free School District', 'http://www2.lhric.org/pleasantville/'],
['Rye City School District', 'http://www.ryecityschools.lhric.org/'],
['Rye Neck Union Free School District', 'http://www.ryeneck.k12.ny.us/default.aspx'],
['Somers Central School District', 'http://https://www.edline.net/pages/Somers_CSD'],
['Valhalla Union Free School', 'http://www.valhalla.k12.ny.us/'],
['White Plains City School District', 'http://www.wpcsd.k12.ny.us/'],
['Yorktown Central School District', 'http://www.yorktowncsd.org/'],
['Wyoming Central School District', 'http://www.wyoming.k12.ny.us/']
]



fin = []



for grudb in grudb_list:
    sch = grudb[0].split('Central School District')[0]
    sch = sch.split('Union Free School')[0]
    sch = sch.split('School District')[0]
    sch = sch.split('Free School')[0]

    fin.append(sch)


for i in sorted(fin):

    #print(str(i.text), '\n', i.get('href'))



























